commit_message: "[ci skip]"
preserve_hierarchy: true
files:
  - source: "/src/i18n/en_US/**/*"
    translation: "/src/i18n/%locale_with_underscore%/**/%original_file_name%"
  - source: "/src/docs/**/*"
    translation: "/src/i18n/%locale_with_underscore%/docusaurus-plugin-content-docs/current/**/%original_file_name%"
  - source: "/src/blog/**/*"
    translation: "/src/i18n/%locale_with_underscore%/docusaurus-plugin-content-blog/**/%original_file_name%"
