commit_message: "[ci skip]"
preserve_hierarchy: true
files:
  - source: "/i18n/en/**/*"
    translation: "/i18n/%locale_with_underscore%/**/%original_file_name%"
  - source: "/docs/**/*"
    translation: "/i18n/%locale_with_underscore%/docusaurus-plugin-content-docs/current/**/%original_file_name%"
  - source: "/blog/**/*"
    translation: "/i18n/%locale_with_underscore%/docusaurus-plugin-content-blog/**/%original_file_name%"
