module.exports = {
  someSidebar: {
    项目简介: ["00-0-Docs", "00-1-Why-Newbe-Claptrap"],
    快速入门: [
      "01-0-Quick-Start",
      "01-1-Create-Project",
      "01-2-Simple-Event-Flow",
      "01-3-New-Claptrap",
      "01-4-Start-With-Minion",
    ],
    术语表: [
      "02-0-Glossary",
      "02-1-Actor-Pattern",
      "02-10-Claptrap-Identity",
      "02-11-Claptrap-Box",
      "02-12-Claptrap-Lifetime-Scope",
      "02-13-Serialization",
      "02-14-Minimal-Competing-Resources",
      "02-2-Event-Sourcing",
      "02-3-Claptrap",
      "02-4-Minion",
      "02-5-Event",
      "02-6-State",
      "02-7-State-Snapshot",
      "02-8-Claptrap-Design",
      "02-9-Claptrap-Factory",
    ],
    "项目样例-火车售票": [
      "03-0-Newbe-Claptrap-Ticketing",
      "03-1-Design",
      "03-2-Impletmentation",
      "03-3-Deployment",
    ],
  },
};
